version: "3.8"
services:
  bot:
    image: bitl_craig
    working_dir: /bitl_craig
    volumes: 
      - ./data/rec:/bitl_craig/rec
      - ./config.json:/bitl_craig/config.json:ro
    networks:
      - host
    ports:
      - "80:80"
    command: bash -c "chmod a+x ./init.sh; ./init.sh"
networks:
  host: