services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./install.config
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - 'db_data:/var/lib/postgresql/data'

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  craig:
    build: .
    env_file:
      - ./install.config
    ports:
      - "3000:3000"
      - "5029:5029"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    volumes:
      - 'craig_rec:/app/rec'
      - './install.config:/app/install.config:ro'
      - './prisma:/app/prisma'
      - './apps/bot/config:/app/apps/bot/config'
      - './apps/tasks/config:/app/apps/tasks/config'

volumes:
  db_data:
  craig_rec:
