packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@types/common-tags': ^1.8.4
  '@types/node': ^22.18.0
  common-tags: ^1.8.2
  cron: ^4.3.4
  destr: ^2.0.5
  ioredis: ^6.0.0
  tsdown: 0.22.14
  tsx: ^4.23.13
  typescript: ^7.0.2
allowBuilds:
  '@discordjs/opus': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  es5-ext: true
  esbuild: true
  pnpm: true
  prisma: true
  sharp: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
overrides:
  "sharp": "0.34.5"
  "supports-color": "8.1.1"
minimumReleaseAgeExclude:
- "@snazzah/davey*"
patchedDependencies:
  svelte-awesome-color-picker: patches/svelte-awesome-color-picker.patch
allowUnusedPatches: true
