name: Dryrun
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Write .env
        run: |
          cat > .env << 'EOF'
          DISCORD_BOT_TOKEN=test
          DISCORD_APP_ID=273518732733710337
          DEVELOPMENT_GUILD_ID=
          DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"
          EOF

      - name: Write apps/dashboard/.env
        run: |
          cat > apps/dashboard/.env << 'EOF'
          CLIENT_ID=999999999999999999
          CLIENT_SECRET=test

          GOOGLE_CLIENT_ID=test
          GOOGLE_CLIENT_SECRET=test

          MICROSOFT_CLIENT_ID=test
          MICROSOFT_CLIENT_SECRET=test

          DROPBOX_CLIENT_ID=test
          DROPBOX_CLIENT_SECRET=test

          APP_URI=http://localhost:3000
          JWT_SECRET=1234
          EOF

      - name: Build Bot
        run: cd apps/bot && yarn prisma:generate && yarn build

      - name: Build Dashboard
        run: cd apps/dashboard && yarn prisma:generate && yarn build

      - name: Build Download
        run: cd apps/download && yarn build

      - name: Build Tasks
        run: cd apps/tasks && yarn prisma:generate && yarn build
