name: Manypkg
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    name: Lint monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --production=false

      - name: Run Manypkg
        run: yarn lint:monorepo
